### ISSUE TITLE
Divide by zero exception

### ISSUE THREAD

**Issue by seltzdesign** [mrvux/dx11-vvvv#100]
I'm posting the error here again. This error is logged in the TTY renderer seemingly every frame (around 50 times per second). I am using vvvv45beta31.2 x64. The only DX11 nodes I use are in mremdmod2.1 and is basically one of the examples md provided.

```
00:16:00 ERR : System.DivideByZeroException in VVVV.PluginInterfaces: Attempted to divide by zero.

Stacktrace:
   at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Nodes.Renderers.Graphics.DX11VolumeRendererNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.Nodes.Renderers.Graphics.DX11VolumeRendererNode.Render(DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)

00:16:00 ERR : System.DivideByZeroException in VVVV.PluginInterfaces: Attempted to divide by zero.

Stacktrace:
   at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Nodes.Renderers.Graphics.DX11VolumeRendererNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)
```

Can you give me some contact details, so I could send you the patch? I dont want to post it publicly. Email: seltz.design@gmail.com or skype: kloppsi83. Thank you!

**Comment by youngjiggi** [comment]
Hello mrvux, I am having the same error messages as with seltzdesign. I am using vvvv45beta33.7 x64 with the most recent dx11 pack you have released (vvvv-packs-dx11-b33x-x64). I am working on spotlights example from the MRE.Mdmod2.pack. From this post (http://vvvv.org/forum/divided-by-zero-exception-in-dx11-node#comment-186195) seltzdesign suggests there is some kind of switch inside the MRE node? Do you happen to remember what the issue was ? Best, yj (youngjaechung@gmail.com)

**Comment by mrvux** [comment]
If i remember right there's a volume renderer receiving nil input.
With b33+ entering debug mode should show that node in red
