### ISSUE TITLE
Kinect2 face crash

### ISSUE THREAD

**Issue by davidcinimod** [mrvux/dx11-vvvv#188]
Got that null Reference exception while using face on x64 win8 master branch vvvvbeta33.3

System.NullReferenceException: Object reference not set to an instance of an object.
   at VVVV.MSKinect.Nodes.KinectFaceNode.SkeletonReady(Object sender, BodyFrameArrivedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

**Comment by mrvux** [comment]
Build does copy face dlls properly now, so it is usable out of the box
