### ISSUE TITLE
Framerate drop, crashes, and stacktraces with 33.7 pack

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#207]
With the new b33.7-x85 vs. b33x-86 pack, I am getting about half the framerate, and frequent system crashes and stacktraces when I have renderers on outputs of two graphics cards (GTX780s). With 33x, I get roughly 70fps, and 33.7 I get about 32fps. But the worst part is the hard system crashes, which can happen in minutes to hours, but almost always within 12-24 hours. While I usually get a crash, sometimes vvvv just starts getting stacktraces:

ERR : Exception caused by node during render :/1000/73/77/0/51
 ERR : SlimDX.DXGI.DXGIException in SlimDX: DXGI_ERROR_DEVICE_REMOVED: Hardware device removed. (-2005270523)
 
 Stacktrace:
    at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
    at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
    at SlimDX.DXGI.SwapChain..ctor(Factory factory, ComObject device, SwapChainDescription description)
    at FeralTic.DX11.Resources.DX11SwapChain..ctor(DX11RenderContext context, IntPtr handle, Format format, SampleDescription sampledesc, Int32 rate, Int32 bufferCount)
    at VVVV.DX11.Nodes.DX11RendererNode.Update(IPluginIO pin, DX11RenderContext context)
    at VVVV.DX11.Nodes.DX11RendererNode.Render(DX11RenderContext context)
    at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)
 
  -  : Stack Trace
  -  :    at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
    at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
    at SlimDX.DXGI.SwapChain..ctor(Factory factory, ComObject device, SwapChainDescription description)
    at FeralTic.DX11.Resources.DX11SwapChain..ctor(DX11RenderContext context, IntPtr handle, Format format, SampleDescription sampledesc, Int32 rate, Int32 bufferCount)
    at VVVV.DX11.Nodes.DX11RendererNode.Update(IPluginIO pin, DX11RenderContext context)
    at VVVV.DX11.Nodes.DX11RendererNode.Render(DX11RenderContext context)
    at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)

This is happening in a patch that is sending one layer to six renderers, three on each graphics card, using the ViewPort node to map the displays. The above happens for each of all six renderer nodes, not just the second card.

I have updated nVidia drivers, and tried SLI on, off, and activate all displays with no change. By just changing the DX11 pack back to 33x, I do not see the problem (but then see spurious black textures from DX9->DX11 video).

**Comment by SanchTv** [comment]
I noticed also a big framedrop with the last pack

**Comment by mrvux** [comment]
Fixed swapchain issue in https://github.com/mrvux/dx11-vvvv/commit/5e1ef25ad32a11989ba3bd27a3ac742c018a3446
Thanks for reporting

**Comment by mrvux** [comment]
As a side note since it's a rather nasty bug, I will update the packs this week with the fixed version, for now you can do a custom build.

**Comment by mediadog** [comment]
I can see how this would cause the FPS drop, this is also causing the crashes?  I'll try the alpha ASAP - thank you sir!

**Comment by mediadog** [comment]
Built the alpha and it has now run 24 hours on four machines with no crashes or stacktraces, and hitting the same 70fps as 33x.  Yowzah!
