### ISSUE TITLE
0.6 hangs 34.2 x86 at splash screen

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#233]
Fresh install of 34.2 x86 on Win7 Enterprise, 0.6 only pack, and vvvv hangs at the grey splash screen.  Clicking on the splash screen makes it go away, and vvvv is on the taskbar, but no patch window.  Forcing close of vvvv gives "stopped working" dialogue, selecting close gives "Runtime error 216 at 00406792".

/showexceptions log:

------------------------------------------------------------------------------
Exception log with detailed tech info. Generated on 12/29/2015 11:59:13 AM.
You may send it to the application vendor, helping him to understand what had happened.
 Application title: 
 Application file: D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\vvvv.exe
------------------------------------------------------------------------------
Exception class: EClrException
Exception message: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'VVVV.DX11.Factories.DX11NodesFactory'.

Resulting in: Cannot activate part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\packs\dx11\factories")

Resulting in: Cannot get export 'VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' from part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\packs\dx11\factories")

Resulting in: Cannot set import 'VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' on part 'VVVV.Hosting.HDEHost'.
Element: VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.Hosting.HDEHost
.
Exception address: 00000000
------------------------------------------------------------------------------
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'VVVV.DX11.Factories.DX11NodesFactory'.

Resulting in: Cannot activate part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\packs\dx11\factories")

Resulting in: Cannot get export 'VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' from part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\packs\dx11\factories")

Resulting in: Cannot set import 'VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' on part 'VVVV.Hosting.HDEHost'.
Element: VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.Hosting.HDEHost

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at VVVV.Hosting.HDEHost.Initialize(IVVVVHost vvvvHost, INodeBrowserHost nodeBrowserHost, IWindowSwitcherHost windowSwitcherHost, IKommunikatorHost kommunikatorHost)
------------------------------------------------------------------------------
Main thread ID = 5820
Exception thread ID = 5820
------------------------------------------------------------------------------
Exception stack
Stack list, generated 12/29/2015 11:59:13 AM
[0064C7E9]{vvvv.exe    } ClrUtils.ClrCheck (Line 1048, "ClrUtils.pas" + 2)
[007D62E7]{vvvv.exe    } Globals.TMGlobals.Initialize (Line 584, "Globals.pas" + 14)
[007A5560]{vvvv.exe    } Main.TMMainForm.FormCreate (Line 102, "Main.pas" + 50)
[00520F65]{vvvv.exe    } Vcl.Forms.TCustomForm.DoCreate (Line 3693, "Vcl.Forms.pas" + 3)
[00520BA9]{vvvv.exe    } Vcl.Forms.TCustomForm.AfterConstruction (Line 3577, "Vcl.Forms.pas" + 1)
[00406E0D]{vvvv.exe    } System.@AfterConstruction (Line 14213, "System.pas" + 2)
[00520B79]{vvvv.exe    } Vcl.Forms.TCustomForm.Create (Line 3572, "Vcl.Forms.pas" + 35)
[0052B5A6]{vvvv.exe    } Vcl.Forms.TApplication.CreateForm (Line 10283, "Vcl.Forms.pas" + 13)
[00A60605]{vvvv.exe    } vvvv.vvvv (Line 41, "" + 6)
------------------------------------------------------------------------------
Call stack for main thread
Stack list, generated 12/29/2015 11:59:14 AM
[77DD0C82]{ntdll.dll   } ZwGetContextThread
------------------------------------------------------------------------------
System   : Windows 7 Professional, Version: 6.1, Build: 1DB1, "Service Pack 1"
Processor: Intel, Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz, 3500 MHz MMX SSE SSE2 SSE3 SSSE3 64 bits DEP
Memory: 16277; free 12699
Display  : 1920x1080 pixels, 32 bpp
------------------------------------------------------------------------------
List of loaded modules:
[00400000] D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\vvvv.exe
           34.2.1324.0 - 34.2.1324.0
           vvvv - a multipurpose toolkit
           Unit versioning information:
             JCL\source\common $URL$ $Revision$ $Date$
[02610000] D:\HELIOT~1\SW\vvvv\vvvv_45beta31.2_x86\lib\thirdparty\x86\AddFlow5.ocx
<10000000> 5.4.0.19 - 5, 4, 0, 19
           AddFlow ActiveX Control
[02900000] C:\Windows\system32\myokent.dll
<00400000> 1.75.0.53 - 1.75.0.053
           MIDI Yoke Junction NT
[03B10000] D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\lib\thirdparty\x86\dxerr9.dll
<10000000> (no module version info)
[07D20000] D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\lib\core\SlimDX.dll
<10000000> (no module version info)
[10000000] D:\Heliotrope\SW\vvvv\vvvv_45beta34.2_x86\lib\thirdparty\x86\ode.dll
           0.8.14.0 - 0, 8, 14, 0
           ODE Single Precision DLL for DelphiODE
[59850000] C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
           12.0.51209.34209 - 12.0.51209.34209 built by: FX452RTMGDR
           Dia based SymReader
[59C90000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Reflection\b81a703e1f50365d6cf4c9c95a9930eb\System.Reflection.ni.dll
           4.0.30319.34209 - 4.0.30319.34209
           System.Reflection.dll
[59D20000] C:\Windows\system32\nvd3dum.dll
           10.18.13.6143 - 10.18.13.6143
           NVIDIA WDDM D3D Driver, Version 361.43 
[5AA80000] C:\Windows\system32\d3dx9_33.dll
           9.18.904.15 - 9.18.904.0015
[5ADF0000] C:\Windows\system32\d3dx9_38.dll
           9.23.949.2378 - 9.23.949.2378
[5B1C0000] C:\Windows\system32\quartz.dll
           6.6.7601.18741 - 6.6.7600.16385 (win7_rtm.090713-1255)
           DirectShow Runtime.
[5B340000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Runt9e372c89#\2cc820a5e544f9359fc24d1b83929d1d\System.Runtime.InteropServices.ni.dll
           4.0.30319.34209 - 4.0.30319.34209
           System.Runtime.InteropServices.dll
[5B3A0000] C:\Windows\system32\MFC42.DLL
           6.6.8064.0 - 6.06.8063.0
           MFCDLL Shared Library - Retail Version
[5B8F0000] C:\Windows\system32\d3d9.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Direct3D 9 Runtime
[5BB10000] C:\Windows\system32\dsound.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           DirectSound
[5BB90000] C:\Windows\system32\ODBC32.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           ODBC Driver Manager
[5BF90000] C:\Windows\system32\nvwgf2um.dll
           10.18.13.6143 - 10.18.13.6143
           NVIDIA D3D10 Driver, Version 361.43 
[60300000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Collections\24a4c7b82b483cc3b5ab8e587593482a\System.Collections.ni.dll
           4.0.30319.34209 - 4.0.30319.34209
           System.Collections.dll
[64FD0000] C:\Windows\system32\tapi32.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft® Windows(TM) Telephony API Client DLL
[65180000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Runtime\a5d5b495ed4752c3b73b5d1938ee9a78\System.Runtime.ni.dll
           4.0.30319.34209 - 4.0.30319.34209
           System.Runtime.dll
[65190000] C:\Windows\system32\odbcint.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           ODBC Resources
[659B0000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Threading\4b925df23c49f7739afb59433c0a5394\System.Threading.ni.dll
           4.0.30319.34209 - 4.0.30319.34209
           System.Threading.dll
[67990000] C:\Windows\system32\AVIFIL32.DLL
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft AVI File support library
[681B0000] C:\Windows\syswow64\dbghelp.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Image Helper
[682A0000] C:\Windows\system32\d3d11.dll
           6.2.9200.16570 - 6.2.9200.16570 (win8_gdr.130327-1526)
           Direct3D 11 Runtime
[68420000] C:\Windows\system32\dxgi.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           DirectX Graphics Infrastructure
[690E0000] C:\Windows\system32\DXGIDebug.dll
           9.30.9600.16384 - 9.30.9600.16384
           DXGI Debug Binary
[69100000] C:\Windows\system32\DWrite.dll
           6.2.9200.17568 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           Microsoft DirectX Typography Services
[69490000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\ac49b0362a9648df9d2f437d27ff54ff\System.Windows.Forms.ni.dll
           4.0.30319.34251 - 4.0.30319.34251 built by: FX452RTMGDR
           .NET Framework
[6A530000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\fe41e3eae34ac29f3c1f03a03d8aa1af\System.Drawing.ni.dll
           4.0.30319.34270 - 4.0.30319.34270 built by: FX452RTMGDR
           .NET Framework
[6B1A0000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\c61bafa9d029e3f2bf83bd5af3f1f5ac\System.Core.ni.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           .NET Framework
[6B850000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\3d6ee4ffbd9a86ac1e7b01800b6fe9c7\System.Xml.ni.dll
           4.0.30319.34234 - 4.0.30319.34234 built by: FX452RTMGDR
           .NET Framework
[6BFD0000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System\d18e2115a3270f89663fce831547f534\System.ni.dll
           4.0.30319.34238 - 4.0.30319.34238 built by: FX452RTMGDR
           .NET Framework
[6C970000] C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\d1265d6159ea876f9d63ea4c1361b587\mscorlib.ni.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           Microsoft Common Language Runtime Class Library
[6DCA0000] C:\Windows\system32\security.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Security Support Provider Interface
[6DD10000] C:\Windows\SysWOW64\devenum.dll
           6.6.7600.16385 - 6.6.7600.16385 (win7_rtm.090713-1255)
           Device enumeration.
[6DD30000] C:\Windows\system32\dinput8.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft DirectInput
[6DD70000] C:\Windows\system32\Icmp.Dll
<6DD80000> 6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           ICMP DLL
[6DD80000] C:\Windows\system32\MsVfW32.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Video for Windows DLL
[6DE10000] C:\Windows\system32\AUDIOSES.DLL
           6.1.7601.18741 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Audio Session
[6DF10000] C:\Windows\system32\msdmo.dll
           6.6.7601.17514 - 6.6.7601.17514 (win7sp1_rtm.101119-1850)
           DMO Runtime
[6F390000] C:\Windows\system32\ksuser.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           User CSA Library
[6FDD0000] C:\Windows\system32\msimg32.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           GDIEXT Client DLL
[704A0000] C:\Windows\system32\MSVCP100.dll
           10.0.40219.325 - 10.00.40219.325
           Microsoft® C Runtime Library
[708C0000] C:\Windows\system32\HID.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Hid User Library
[708D0000] C:\Windows\system32\WINSTA.dll
           6.1.7601.18540 - 6.1.7601.18540 (win7sp1_gdr.140716-1508)
           Winstation Library
[71220000] C:\Windows\system32\wtsapi32.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Remote Desktop Session Host Server SDK APIs
[71330000] C:\Windows\system32\dwmapi.dll
           6.1.7601.18917 - 6.1.7601.18917 (win7sp1_gdr.150709-0600)
           Microsoft Desktop Window Manager API
[71550000] C:\Windows\system32\PROPSYS.dll
           7.0.7601.17514 - 7.00.7600.16385 (win7_rtm.090713-1255)
           Microsoft Property System
[71650000] C:\Windows\system32\MMDevAPI.DLL
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           MMDevice API
[71C70000] C:\Windows\system32\MSVCR100.dll
           10.0.40219.325 - 10.00.40219.325
           Microsoft® C Runtime Library
[72200000] C:\Windows\system32\uxtheme.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft UxTheme Library
[72500000] C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\908075c4922acdf834c67ac802814c9d\System.Configuration.ni.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           System.Configuration.dll
[725F0000] C:\Windows\Microsoft.NET\Framework\v4.0.30319\nlssorting.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           Microsoft Collation Support
[72680000] C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           Microsoft .NET Runtime Just-In-Time Compiler
[72700000] C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           Microsoft .NET Runtime Common Language Runtime - WorkStation
[72DA0000] C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
           4.0.30319.34209 - 4.0.30319.34209 built by: FX452RTMGDR
           Microsoft .NET Runtime Execution Engine
[72E90000] C:\Windows\system32\MSVCR120_CLR0400.dll
           12.0.51720.34280 - 12.00.51720.34280 built by: FX452RTMGDR
           Microsoft® C Runtime Library
[73670000] C:\Windows\system32\MSACM32.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft ACM Audio Filter
[73690000] C:\Windows\system32\winmm.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           MCI API DLL
[736D0000] C:\Windows\system32\AVRT.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Multimedia Realtime Runtime
[736E0000] C:\Windows\system32\olepro32.dll
           6.1.7601.17514 - 6.1.7601.17514
[73700000] C:\Windows\system32\RpcRtRemote.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Remote RPC Extension
[73710000] C:\Windows\system32\WINNSI.DLL
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Network Store Information RPC interface
[73740000] C:\Windows\system32\bcrypt.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Cryptographic Primitives Library (Wow64)
[737A0000] C:\Windows\system32\iphlpapi.DLL
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           IP Helper API
[738F0000] C:\Windows\system32\SECUR32.DLL
           6.1.7601.19045 - 6.1.7601.19045 (win7sp1_gdr.151019-1254)
           Security Support Provider Interface
[73900000] C:\Windows\system32\rsaenh.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Enhanced Cryptographic Provider
[73940000] C:\Windows\system32\CRYPTSP.dll
           6.1.7601.18741 - 6.1.7601.18741 (win7sp1_gdr.150202-1526)
           Cryptographic Service Provider API
[73970000] C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\comctl32.dll
           6.10.7601.18837 - 6.10 (win7_rtm.090713-1255)
           User Experience Controls Library
[73CE0000] C:\Windows\system32\POWRPROF.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Power Profile Helper DLL
[73D30000] C:\Windows\system32\mscoree.dll
           4.0.40305.0 - 4.0.40305.0 (Main.040305-0000)
           Microsoft .NET Runtime Execution Engine
[742D0000] C:\Windows\system32\d3d8thk.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Direct3D OS Thunk Layer
[744A0000] C:\Windows\system32\wdmaud.drv
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Winmm  audio system driver
[74740000] C:\Windows\system32\msacm32.drv
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Sound Mapper
[74750000] C:\Windows\system32\midimap.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft MIDI Mapper
[74AC0000] C:\Windows\system32\wsock32.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Socket 32-Bit DLL
[752B0000] C:\Windows\system32\ntmarta.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows NT MARTA provider
[752E0000] C:\Windows\SysWOW64\nvinit.dll
           10.18.13.6143 - 10.18.13.6143
           NVIDIA shim initialization dll, Version 361.43 
[75310000] C:\Windows\system32\winspool.drv
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Spooler Driver
[75370000] C:\Windows\system32\version.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Version Checking and File Installation Libraries
[75440000] C:\Windows\syswow64\CRYPTBASE.dll
           6.1.7601.19045 - 6.1.7601.19045 (win7sp1_gdr.151019-1254)
           Base cryptographic API DLL
[75450000] C:\Windows\syswow64\SspiCli.dll
           6.1.7601.19045 - 6.1.7601.19045 (win7sp1_gdr.151019-1254)
           Security Support Provider Interface
[754B0000] C:\Windows\syswow64\DEVOBJ.dll
           6.1.7601.17621 - 6.1.7601.17621 (win7sp1_gdr.110523-2108)
           Device Information Set DLL
[754D0000] C:\Windows\syswow64\USP10.dll
           1.626.7601.19054 - 1.0626.7601.19054 (win7sp1_gdr.151103-0600)
           Uniscribe Unicode script processor
[75570000] C:\Windows\system32\IMM32.DLL
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Multi-User Windows IMM32 API Client DLL
[755D0000] C:\Windows\SysWOW64\sechost.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Host for SCM/SDDL/LSA Lookup APIs
[755F0000] C:\Windows\syswow64\CLBCatQ.DLL
           2001.12.8530.16385 - 2001.12.8530.16385 (win7_rtm.090713-1255)
           COM+ Configuration Catalog
[75680000] C:\Windows\syswow64\ADVAPI32.dll
           6.1.7601.18939 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Advanced Windows 32 Base API
[75730000] C:\Windows\syswow64\msvcrt.dll
           7.0.7601.17744 - 7.0.7601.17744 (win7sp1_gdr.111215-1535)
           Windows NT CRT DLL
[757E0000] C:\Windows\syswow64\WLDAP32.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Win32 LDAP API DLL
[759F0000] C:\Windows\syswow64\shell32.dll
           6.1.7601.18952 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Shell Common Dll
[76770000] C:\Windows\syswow64\SHLWAPI.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Shell Light-weight Utility Library
[767D0000] C:\Windows\syswow64\LPK.dll
           6.1.7601.18985 - 6.1.7601.18985 (win7sp1_gdr.150901-1452)
           Language Pack
[767E0000] C:\Windows\syswow64\WINTRUST.dll
           6.1.7601.18839 - 6.1.7601.18839 (win7sp1_gdr.150427-0707)
           Microsoft Trust Verification APIs
[76810000] C:\Windows\syswow64\MSCTF.dll
           6.1.7601.18731 - 6.1.7600.16385 (win7_rtm.090713-1255)
           MSCTF Server DLL
[768E0000] C:\Windows\syswow64\CFGMGR32.dll
           6.1.7601.17621 - 6.1.7601.17621 (win7sp1_gdr.110523-2108)
           Configuration Manager DLL
[76910000] C:\Windows\syswow64\oleaut32.dll
           6.1.7601.18679 - 6.1.7601.18679
[76AC0000] C:\Windows\syswow64\imagehlp.dll
           6.1.7601.18288 - 6.1.7601.18288 (win7sp1_gdr.131018-1533)
           Windows NT Image Helper
[76AF0000] C:\Windows\syswow64\WS2_32.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Socket 2.0 32-Bit DLL
[76B30000] C:\Windows\syswow64\NSI.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           NSI User-mode interface DLL
[76B40000] C:\Windows\syswow64\USER32.dll
           6.1.7601.19061 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Multi-User Windows USER API Client DLL
[76CA0000] C:\Windows\syswow64\comdlg32.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Common Dialogs DLL
[76D20000] C:\Windows\syswow64\GDI32.dll
           6.1.7601.18898 - 6.1.7601.18898 (win7sp1_gdr.150617-0600)
           GDI Client DLL
[76DB0000] C:\Windows\syswow64\KERNELBASE.dll
           6.1.7601.19045 - 6.1.7601.18015 (win7sp1_gdr.121129-1432)
           Windows NT BASE API Client DLL
[76E00000] C:\Windows\syswow64\RPCRT4.dll
           6.1.7601.19045 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Remote Procedure Call Runtime
[76F80000] C:\Windows\syswow64\ole32.dll
           6.1.7601.18915 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft OLE for Windows
[770E0000] C:\Windows\syswow64\MSASN1.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           ASN.1 Runtime APIs
[770F0000] C:\Windows\syswow64\CRYPT32.dll
           6.1.7601.18839 - 6.1.7601.18839 (win7sp1_gdr.150427-0707)
           Crypto API32
[77220000] C:\Windows\syswow64\kernel32.dll
           6.1.7601.19045 - 6.1.7601.18015 (win7sp1_gdr.121129-1432)
           Windows NT BASE API Client DLL
[77330000] C:\Windows\syswow64\SetupApi.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Setup API
[77D80000] C:\Windows\syswow64\PSAPI.DLL
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Process Status Helper
[77DB0000] C:\Windows\SysWOW64\ntdll.dll
           6.1.7601.19045 - 6.1.7600.16385 (win7_rtm.090713-1255)
           NT Layer DLL
------------------------------------------------------------------------------
Active Controls hierarchy:
TMSplashScreen "MSplashScreen"
------------------------------------------------------------------------------

**Comment by mediadog** [comment]
Same behavior here with 34.2 x64, and 33.7 x86 and x64.

**Comment by mrvux** [comment]
Mm curious if could be related with directwrite issue you have, as also moved that to framework 4.5.

Also what language is your OS? Might be related.

**Comment by mediadog** [comment]
I have made sure the old bad libs that were causing the Text issue are gone.  This is with US English Win7 Enterprise.  I just tested it on a Win7 x64 Enterprise laptop with Intel HD 4000 graphics, same thing (other two systems are nVidia GTX 770/780s with latest drivers).

I can move the 0.6 version out and put the 33.7 version back and it works great.  Do nothing but replace the 33.7 dx11 with the 0.6, hangs again.

Let me know if there are any diagnostics I can do.  I guess I can try building from sources...

**Comment by mrvux** [comment]
Mm ok, only thing I can see would be win7 throwing error on level flag instead of ignoring it, will so a quick build without it one sec

**Comment by mrvux** [comment]
[FeralTic.zip](https://github.com/mrvux/dx11-vvvv/files/74364/FeralTic.zip)

Ok just commented out that flag quickly, can you check to replace this lib (packs/dx11/lib/core), x64 version

**Comment by mrvux** [comment]
If that is the issue, will have to add some win8 check and post a new build ;)

**Comment by mediadog** [comment]
Same behavior with the new FeralTic.  I also tried building from current github (using VS 2013), both release and debug, same thing.

I've looked at my environment but can find nothing that might be conflicting, I even set the root.v4p back to the original to take all my plugins out of the mix.

I'll try it on a Win8 machine, and a virgin Win7 box.

**Comment by mrvux** [comment]
If you have debug run, try commenting:
DirectWriteFontUtils.SetFontEnum(this.hdehost, this.DirectWriteFactory);in nodefactory (line 85)

Only thing I added there, so can't see anything else for now

**Comment by mediadog** [comment]
Will try that.  Just tested on Win8.1, works fine.

**Comment by mrvux** [comment]
Also maybe try to delete VVVV.DX11.Nodes.Text.dll , see if it comes from that, just in case....

**Comment by mediadog** [comment]
Commented out that line (85) in DX11nodesFactory.cs and built x86 debug, copied whole dx11 folder under deploy/debug/x86/packs to 34.2 x86 packs folder, verified lib timestamps, same hang.

**Comment by mhusinsky** [comment]
same for me here: win10 runs fine, win8 (not 8.1) hangs at startup. tried rebuilding & dll deletion -> does not make any difference.

**Comment by mediadog** [comment]
Yup, deleting the text dll no diff.  Thanks mhusinsky, saved me trying Win10!

**Comment by mrvux** [comment]
ok guess I get it, my bad :)

**Comment by mrvux** [comment]
[D3DCompiler_47.zip](https://github.com/mrvux/dx11-vvvv/files/74405/D3DCompiler_47.zip)
Try to copy that to same folder as vvvv.exe, that should work then

**Comment by mediadog** [comment]
Copied D3DCompiler_47.dll next to 34.2 x86 vvvv.exe, same behavior (this is with your DX11 0.6 release).

**Comment by mhusinsky** [comment]
confirmed. tried with b32.4 x86 and a34.102 x64 - still hangs with exception

**Comment by mrvux** [comment]
[FeralTic.zip](https://github.com/mrvux/dx11-vvvv/files/74522/FeralTic.zip)
Ok did checks to test if win8 is available for level creation, and added another one for compiler (x64 build).
Please report if it works and i'll push the commit in that case

**Comment by mediadog** [comment]
The above FeralTic.dll works for 34.2 x86 and 0.6!  Yeehaah!  But not for 34.2 x86 which I assume it was not supposed to...

**Comment by mediadog** [comment]
And that was on Win7 x64 Enterprise.

**Comment by mrvux** [comment]
Yeah, makes sense, as it's a 64 bits version, ok I'll push changes then

**Comment by mrvux** [comment]
Fixed in https://github.com/mrvux/dx11-vvvv/commit/1f1362fda2e1979d3c9dc9b25bca830c1e8f8095
I'll upload fresh build in a min

**Comment by mediadog** [comment]
Saw your shout - I'm very happy to help QA for Win7 as I use it for everything except driving Kinect2s.
