### ISSUE TITLE
Division by zero when creating new renderer window on newest vvvv alpha (35.4) and newest DX11 (1.0.0.34)

### ISSUE THREAD

**Issue by microdee** [mrvux/dx11-vvvv#300]
a .NET Framework exception occurs when a renderer window is created. You can't hide these exceptions nor they can't be made hidden by "/showexceptions false". It's pretty much a show-stopper with permanent installations.
http://i.imgur.com/4MPI7J8.png
`
System.DivideByZeroException: Attempted to divide by zero.
   at VVVV.Utils.VMath.VMath.Zmod(Int32 z, Int32 d)
   at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Nodes.DX11RendererNode.DX11RendererNode_GotFocus(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WmSetFocus(Message& m)
   at System.Windows.Forms.UserControl.WmSetFocus(Message& m)
   at VVVV.DX11.Nodes.DX11RendererNode.WndProc(Message& m)
   at System.Windows.Forms.Control.ActiveXImpl.System.Windows.Forms.IWindowTarget.OnMessage(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by microdee** [comment]
ok I located the problem I'll fix and pull request it. in DX11 renderer the GotFocus event probably fires before that disable shortcuts spread is created or before it's filled up. therefore accessing its first value will cause that exception. basically it's an index is out of range situation.

**Comment by mrvux** [comment]
Yeah seems 4v creates control first, issue is fixed here still already.
