### ISSUE TITLE
Setting temp target renderer to BGRA formats throws errors

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#350]
This was mentioned in a [forum post back in '16](https://discourse.vvvv.org/t/bgra-textures/13809), but guess it's still a problem.  Sadly I need this to feed to program via Spout that only accepts B8G8R8A8_UNorm.  This is with 1.3.1, 35.8_x64, Win7 x64:

00:00:48  -  : Stack Trace
00:00:48  -  :    at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Direct3D11.Texture2D.Build(Device device, Texture2DDescription description, D3D11_SUBRESOURCE_DATA* data)
   at SlimDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at FeralTic.DX11.Resources.DX11RenderTarget2D..ctor(DX11RenderContext context, Int32 w, Int32 h, SampleDescription sd, Format format, Boolean genMipMaps, Int32 mmLevels, Boolean allowUAV, Boolean allowShare)
   at FeralTic.DX11.DX11RenderTargetPool.Lock(Int32 w, Int32 h, Format format, SampleDescription sd, Boolean genMM, Int32 mmLevels, Boolean oneframe, Boolean shared)
   at VVVV.DX11.DX11TempRTRendererNode.OnUpdate(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Update(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Render(DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.RenderNode(DX11Node node)

Also tried latest 1.3.1.41-alpha just in case, same result.

**Comment by mediadog** [comment]
Well the pressure is off, Renderer (DX11 TextureSpread) in 1.3.1 properly generates B8G8R8A8_UNorm output the other program accepts.  So happy happy joy joy, but probably still want to look into it.  I'll mention this in the forum thread.
